name: Publish Chrome Extension

on:
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: npm run build # adjust this to your build command

      - name: Package extension
        run: |
          mkdir -p dist
          # Adjust if your build outputs somewhere else
          zip -r ilovegithub-extension.zip . -x "node_modules/*" "src/*" "*.ts" "webpack.config.js" ".git/*"

      - name: Upload & publish to Chrome Web Store
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: dist/extension.zip
          extension-id: ${{ secrets.EXTENSION_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          publish: true # set to true if you want to publish immediately after upload
