name: Publish Chrome Extension

on:
  push:
    tags:
      - "v*"   # Runs only when a tag starting with 'v' is pushed (e.g., v1.0.0)

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build extension
        run: npm run build # Adjust if you have a build step, else remove

      - name: Pack extension
        run: |
          mkdir -p dist
          zip -r dist/extension.zip . -x '*.git*' 'node_modules/*' 'dist/*'

      - name: Publish to Chrome Web Store
        uses: mobilefirstllc/cws-publish@v2
        with:
          extension_id: ${{ secrets.CHROME_EXTENSION_ID }}
          client_id: ${{ secrets.CHROME_CLIENT_ID }}
          client_secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh_token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          zip_file: dist/extension.zip
